### PR TITLE
Ft community registration #10

### PR DESCRIPTION
**Pull request by Tboy-AK**
## Description
A user can register a community with required details.
This feature was initially built to an extent by @adebayoyeleye, but due changes that could not be handled in the same branch, some files has to be moved to the develop branch before checking out to this new branch.
Run test script to test the feature.
Look through the test file for documentation purposes.

Finishes #10 

## How Has This Been Tested?
-  Tests with Jest
-  Performed focused test on every part of this feature
-  Performed integrated tests on all the features

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by fegoworks — APPROVED** [review]
Great. So I am thinking I will pull this branch, then add my changes here

**Comment by kadirisunday** [comment]
nice work. I will pull these branch to add the front-end design

**Comment by adebayoyeleye** [comment]
> Great. So I am thinking I will pull this branch, then add my changes here

i think you should wait till after the merge to develop branch

**Comment by adebayoyeleye** [comment]
> nice work. I will pull these branch to add the front-end design

i think you should wait till after the merge to develop branch

**Comment by kadirisunday** [comment]
> > nice work. I will pull these branch to add the front-end design
> 
> i think you should wait till after the merge to develop branch

**Review by kadirisunday — APPROVED** [review]

**Pull request merged**
